# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendname', models.CharField(max_length=255, verbose_name='留言人')),
                ('sendtime', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('sendphone', models.CharField(max_length=22, verbose_name='联系方式')),
                ('sendtitle', models.CharField(max_length=255, verbose_name='留言标题')),
                ('sendcontent', models.TextField(verbose_name='留言内容')),
                ('backname', models.CharField(max_length=255, verbose_name='回复人')),
                ('backtime', models.DateTimeField(auto_now=True, verbose_name='回复时间')),
                ('backcontent', models.TextField(verbose_name='回复内容')),
                ('state', models.CharField(max_length=11, verbose_name='留言状态')),
                ('wechat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUser.BWechatUser', verbose_name='微信用户')),
            ],
            options={
                'verbose_name': '留言管理',
                'verbose_name_plural': '留言管理',
            },
        ),
    ]
