# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='process',
            field=models.CharField(default='待回复', max_length=11, verbose_name='留言进度'),
        ),
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(default='私密', max_length=11, verbose_name='留言状态'),
        ),
    ]
