# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_auto_20180522_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='backcontent',
            field=models.TextField(blank=True, null=True, verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='backname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='message',
            name='wechat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BUser.BWechatUser', verbose_name='微信用户'),
        ),
    ]
