# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0004_auto_20181010_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file0',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/message', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file1',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/message', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file2',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/message', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file3',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/message', verbose_name='文件'),
        ),
    ]
