# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiXiang',
            fields=[
                ('bh', models.BigAutoField(primary_key=True, serialize=False, verbose_name='事项编号')),
                ('name', models.CharField(max_length=511, verbose_name='事项名称')),
                ('bldx', models.CharField(max_length=255, verbose_name='办理对象')),
                ('sxzt', models.CharField(default='草稿', max_length=50, verbose_name='事项状态')),
                ('cjsj', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('znbm', models.CharField(blank=True, max_length=255, null=True, verbose_name='职能类别')),
                ('dccs', models.IntegerField(default=1, verbose_name='到场次数')),
                ('zgbm', models.CharField(max_length=255, verbose_name='主管部门')),
                ('sljg', models.CharField(max_length=255, verbose_name='受理机构')),
                ('slyj', models.TextField(verbose_name='设立依据')),
                ('bltj', models.TextField(verbose_name='办理条件')),
                ('sfsf', models.BooleanField(default=False, verbose_name='是否收费')),
                ('sfyj', models.TextField(verbose_name='收费依据')),
                ('fdqx', models.CharField(default='5个工作日', max_length=255, verbose_name='法定期限')),
                ('clqx', models.CharField(default='5个工作日', max_length=255, verbose_name='承诺期限')),
            ],
            options={
                'verbose_name_plural': '事项',
                'verbose_name': '事项',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='ShiXiangType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='事项类型')),
                ('addtime', models.TimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '事项类型',
                'verbose_name': '事项类型',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='shixiang',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebWork.ShiXiangType', verbose_name='事项类型'),
        ),
    ]
