# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shixiang',
            name='bldx',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='bltj',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='clqx',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='dccs',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='fdqx',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='sfsf',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='sfyj',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='sljg',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='slyj',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='zgbm',
        ),
        migrations.RemoveField(
            model_name='shixiang',
            name='znbm',
        ),
        migrations.AddField(
            model_name='shixiang',
            name='content',
            field=models.TextField(default=1, verbose_name='事项内容'),
            preserve_default=False,
        ),
    ]
