# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWork', '0002_auto_20180517_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='shixiang',
            name='handle',
            field=models.CharField(default='否', max_length=255, verbose_name='网上申办'),
        ),
    ]
