# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BUser', '0001_initial'),
        ('WebWork', '0003_shixiang_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='toShiXiang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backcontent', models.TextField(default='接受办理申请。', null=True, verbose_name='反馈意见')),
                ('state', models.CharField(default='接受', max_length=125, verbose_name='事项状态')),
                ('comment', models.TextField(default='', null=True, verbose_name='评论')),
                ('rank', models.CharField(default='好', max_length=64, verbose_name='评论等级')),
                ('senddata', models.TextField(verbose_name='申请资料')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('xiugaitime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('hold0', models.CharField(blank=True, max_length=255, null=True, verbose_name='保留字段0')),
                ('hold1', models.CharField(blank=True, max_length=255, null=True, verbose_name='保留字段1')),
                ('hold2', models.CharField(blank=True, max_length=255, null=True, verbose_name='保留字段2')),
                ('holdtime0', models.DateTimeField(blank=True, null=True, verbose_name='保留时间字段0')),
                ('shixiang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebWork.ShiXiang', verbose_name='办理事项')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BUser.BUser', verbose_name='办理人员')),
                ('wechctuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BUser.BWechatUser', verbose_name='申请人员')),
            ],
            options={
                'verbose_name': '事项申请',
                'verbose_name_plural': '事项申请',
            },
        ),
    ]
