# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-06 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWork', '0005_auto_20180627_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='shixiang',
            name='file0',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='file1',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='file2',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='file3',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='file4',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='file5',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='file6',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='file7',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='file8',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='file9',
            field=models.FileField(blank=True, default='', null=True, upload_to='WebWork/', verbose_name='附件'),
        ),
    ]
