# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWork', '0006_auto_20181006_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='shixiang',
            name='note0',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='note1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='note2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='note3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='note4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='note5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='note6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='note7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='note8',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='note9',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件说明'),
        ),
    ]
