# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-08 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebWork', '0008_auto_20181007_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='shixiang',
            name='must0',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='must1',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='must2',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='must3',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='must4',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='must5',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='must6',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='must7',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='must8',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='must9',
            field=models.IntegerField(default=0, verbose_name='是否必须'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch0',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch1',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch2',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch3',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch4',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch5',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch6',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch7',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch8',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='shixiang',
            name='switch9',
            field=models.IntegerField(default=0, verbose_name='是否启用'),
        ),
    ]
