# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户名')),
                ('idcard', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='身份证')),
                ('phone', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='电子邮箱')),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户账号')),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户密码')),
                ('logo', models.ImageField(default='BUser/logo/人.png', upload_to='BUser/logo', verbose_name='用户头像')),
                ('hold0', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段0')),
                ('hold1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段1')),
                ('hold2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段2')),
                ('hold3', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段3')),
            ],
            options={
                'verbose_name_plural': '用户记录',
                'verbose_name': '用户记录',
            },
        ),
        migrations.CreateModel(
            name='BWechatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, verbose_name='用户识别号')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户名')),
                ('idcard', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='身份证')),
                ('phone', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='电子邮箱')),
                ('logo', models.ImageField(default='BUser/logo/人.png', upload_to='BUser/logo', verbose_name='用户头像')),
                ('hold0', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段0')),
                ('hold1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段1')),
                ('hold2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段2')),
                ('hold3', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='预留字段3')),
            ],
            options={
                'verbose_name_plural': '微信用户',
                'verbose_name': '微信用户',
            },
        ),
    ]
