# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-09 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buser',
            name='addtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='buser',
            name='changetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='bwechatuser',
            name='addtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='bwechatuser',
            name='changetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
