# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-09 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUser', '0003_auto_20180809_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buser',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='buser',
            name='changetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
