# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUser', '0004_auto_20180809_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='buser',
            name='issuper',
            field=models.IntegerField(default=0, verbose_name='超级管理员标志'),
        ),
        migrations.AddField(
            model_name='buser',
            name='message',
            field=models.IntegerField(default=0, verbose_name='留言权限'),
        ),
        migrations.AddField(
            model_name='buser',
            name='person',
            field=models.IntegerField(default=0, verbose_name='人员权限'),
        ),
        migrations.AddField(
            model_name='buser',
            name='ticket',
            field=models.IntegerField(default=0, verbose_name='叫号权限'),
        ),
        migrations.AddField(
            model_name='buser',
            name='webword',
            field=models.IntegerField(default=0, verbose_name='网上办事权限'),
        ),
    ]
