# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-09 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUser', '0005_auto_20181009_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='buser',
            name='blog',
            field=models.IntegerField(default=0, verbose_name='博客权限'),
        ),
    ]
