# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-09 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bticket',
            name='window',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.BWindow', verbose_name='办理窗口'),
        ),
        migrations.AlterField(
            model_name='bticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BUser.BUser', verbose_name='办理人'),
        ),
    ]
